export const TEST = 'TEST';
export const SIGN_IN = 'SIGN_IN';
export const USER_NAME_INPUT_CHANGE = 'USER_NAME_INPUT_CHANGE';
export const USER_PASSWORD_INPUT_CHANGE = 'USER_PASSWORD_INPUT_CHANGE';
export const SET_UNIQUE_USER_ID = 'SET_UNIQUE_USER_ID';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
